// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBlkxF4iDsovXNE4SWPIa_FfpfJ-PhpNw',
    appId: '1:977365240692:web:fb4ad48e05be7be2033a21',
    messagingSenderId: '977365240692',
    projectId: 'taskmaster-501b4',
    authDomain: 'taskmaster-501b4.firebaseapp.com',
    storageBucket: 'taskmaster-501b4.firebasestorage.app',
    measurementId: 'G-FF64T82CMZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChqB7bkNZeFwhqY4M7sfre-n-3CUURZ20',
    appId: '1:977365240692:android:34296da8e46c5bd4033a21',
    messagingSenderId: '977365240692',
    projectId: 'taskmaster-501b4',
    storageBucket: 'taskmaster-501b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHHAGq2aR9g3qgRXPHmAQlXHYFjxX_0ls',
    appId: '1:977365240692:ios:81f1ce95cff777fe033a21',
    messagingSenderId: '977365240692',
    projectId: 'taskmaster-501b4',
    storageBucket: 'taskmaster-501b4.firebasestorage.app',
    iosBundleId: 'com.example.taskWeak3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHHAGq2aR9g3qgRXPHmAQlXHYFjxX_0ls',
    appId: '1:977365240692:ios:81f1ce95cff777fe033a21',
    messagingSenderId: '977365240692',
    projectId: 'taskmaster-501b4',
    storageBucket: 'taskmaster-501b4.firebasestorage.app',
    iosBundleId: 'com.example.taskWeak3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBlkxF4iDsovXNE4SWPIa_FfpfJ-PhpNw',
    appId: '1:977365240692:web:c4e34c273323a9f0033a21',
    messagingSenderId: '977365240692',
    projectId: 'taskmaster-501b4',
    authDomain: 'taskmaster-501b4.firebaseapp.com',
    storageBucket: 'taskmaster-501b4.firebasestorage.app',
    measurementId: 'G-MLH273BXNP',
  );
}
